# Generated by Django 5.1.5 on 2025-03-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0003_workorder_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='manager',
            field=models.CharField(max_length=16, verbose_name='製造管理担当者'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_number',
            field=models.CharField(max_length=4, verbose_name='工番'),
        ),
    ]
