# Generated by Django 5.1.5 on 2025-03-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0008_alter_workorder_planed_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderprogress',
            name='achievement',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='出来高（％）'),
        ),
        migrations.AlterField(
            model_name='workorderprogress',
            name='daily_result',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='当日実績'),
        ),
    ]
