# Generated by Django 5.1.2 on 2025-03-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0012_alter_workorder_buy_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderprogress',
            name='achievement',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='出来高（％）'),
        ),
        migrations.AlterField(
            model_name='workorderprogress',
            name='daily_result',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='当日実績'),
        ),
    ]
