# Generated by Django 5.1.2 on 2024-11-19 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=10, unique=True, verbose_name='従業員番号')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.CharField(max_length=10, verbose_name='工番')),
                ('subject', models.CharField(max_length=20, verbose_name='件名')),
                ('work_code', models.CharField(choices=[('001', '材料受け入れ'), ('002', 'ノコ切断'), ('003', 'ガス切断'), ('004', 'G仕上げ'), ('005', '罫書・仮付け溶接'), ('006', '段取り替え'), ('007', '製品横持ち'), ('008', '本溶接'), ('009', 'ガス歪取り'), ('010', 'プレス歪取り'), ('011', 'ギザ加工'), ('012', '中間検査'), ('013', 'シャーリング切断'), ('014', 'プレス加工'), ('015', '曲げ加工'), ('016', 'ＮＣ加工'), ('017', '穴あけタップ手加工'), ('018', 'パネル組立・養生'), ('019', 'レーザー加工'), ('402', '塗装・タッチアップ'), ('602', '出荷'), ('701', '作図'), ('903', '現場出張'), ('908', '講習・試験'), ('909', '打ち合せ・会議'), ('999', 'その他')], max_length=3, verbose_name='作業コード')),
                ('work_hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='作業時間')),
                ('date', models.DateField(auto_now_add=True, verbose_name='作業日')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='sagyodenpyo.employee')),
            ],
        ),
    ]
