# Generated by Django 5.1.2 on 2024-11-19 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='作業日')),
                ('achievement', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='出来高（％）')),
                ('daily_result', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当日実績')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='sagyoshiji.workorder')),
            ],
            options={
                'verbose_name': '作業進捗',
                'verbose_name_plural': '作業進捗',
            },
        ),
    ]
