# Generated by Django 5.1.5 on 2025-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0002_workorderprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='release_date',
            field=models.DateField(default='2025-01-01', verbose_name='発行日'),
        ),
    ]
