# Generated by Django 5.1.5 on 2025-03-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0004_alter_workorder_manager_alter_workorder_work_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='work_trenum',
            field=models.CharField(default=0, max_length=3, verbose_name='枝番'),
        ),
    ]
