# Generated by Django 5.1.5 on 2025-03-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0007_alter_workorder_planed_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='planed_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='計画数'),
        ),
    ]
