# Generated by Django 5.1.5 on 2025-03-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0009_alter_workorderprogress_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='end_date',
            field=models.DateField(default='2021/01/10', verbose_name='終了予定日'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='release_date',
            field=models.DateField(default='2021/01/01', verbose_name='発行日'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_date',
            field=models.DateField(default='2021/01/01', verbose_name='作業開始日'),
        ),
    ]
