# Generated by Django 5.1.5 on 2025-03-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0013_alter_workorderprogress_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_group',
            field=models.CharField(choices=[('1', '牛久工場'), ('2', '千葉工場'), ('3', '石下工場'), ('4', 'その他')], max_length=10, verbose_name='製作グループ'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_type',
            field=models.CharField(choices=[('1', 'FB'), ('2', 'PL')], max_length=2, verbose_name='作業種別'),
        ),
    ]
