# Generated by Django 5.1.5 on 2025-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0014_alter_workorder_work_group_alter_workorder_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_trenum',
            field=models.CharField(default='', max_length=3, verbose_name='枝番'),
        ),
    ]
